platform: linux

image_resource:
  type: docker-image
  source: {repository: limaofeng/gradle-alpine}

inputs:
- name: spring-music-res

outputs:
  - name: spring-music

run:
  path: ./spring-music/ci/test.sh
